[ornn]
version = "0.1.9"
log_level = "info"
project_path = "/Users/xuzhang/OrnnSkills"

[llm]
default_provider = "deepseek"

[providers.deepseek]
provider = "deepseek"
model_name = "deepseek-reasoner"
api_key_env_var = "ORNN_DEEPSEEK_API_KEY"

[tracking]
auto_optimize = true
user_confirm = false